name: Unit tests

on:
    push:
    pull_request: 
        branches: [ main ]

jobs:
    run_style_check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: mamba-org/setup-micromamba@v2
              with:
                environment-file: environment.yml
                init-shell: bash
            - run: pycodestyle $(git ls-files "*.py")
              shell: bash -l {0}
    run_unit_tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: mamba-org/setup-micromamba@v2
              with:
                environment-file: environment.yml
                init-shell: bash
            - run: |
                cd assignment-2-python-refresher-seviostanton
                python -m test_my_utils.py
              shell: bash -l {0}
    run_functional_tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: mamba-org/setup-micromamba@v2
              with:
                    environment-file: environment.yml
                    init-shell: bash
            - run: |
                cd assignment-2-python-refresher-seviostanton
                bash test_print_fires.sh
              shell: bash -l {0}